"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  MessageSquare,
  Mic,
  MicOff,
  Play,
  FileText,
  Clipboard,
  Download,
  Loader2,
  AlertCircle,
} from "lucide-react";
import { SAMPLE_TRANSCRIPT } from "@/lib/mockAnalyzer";
import { AIProvider, PROVIDER_INFO } from "@/lib/aiProviders";
import { AIProviderSelector } from "@/components/AIProviderSelector";
import { SOAPData } from "@/lib/types";

interface TranscriptPanelProps {
  transcript: string;
  onTranscriptChange: (val: string) => void;
  onAnalyze: () => void;
  isAnalyzed: boolean;
  isLoading: boolean;
  analysisError: string | null;
  selectedProvider: AIProvider;
  onProviderChange: (p: AIProvider) => void;
  apiKey: string;
  onApiKeyChange: (k: string) => void;
  usedProvider: AIProvider;
  soap: SOAPData;
  isDiagnosisConfirmed: boolean;
  finalDiagnosis: string;
  selectedPlanIds: string[];
  allPlanLabels: Record<string, string>;
}

export function TranscriptPanel({
  transcript,
  onTranscriptChange,
  onAnalyze,
  isAnalyzed,
  isLoading,
  analysisError,
  selectedProvider,
  onProviderChange,
  apiKey,
  onApiKeyChange,
  usedProvider,
  soap,
  isDiagnosisConfirmed,
  finalDiagnosis,
  selectedPlanIds,
  allPlanLabels,
}: TranscriptPanelProps) {
  const [mockListening, setMockListening] = useState(false);
  const [copyMsg, setCopyMsg] = useState("");

  function loadSample() {
    onTranscriptChange(SAMPLE_TRANSCRIPT);
  }

  function toggleMockVoice() {
    setMockListening((prev) => {
      if (!prev) {
        setTimeout(() => {
          onTranscriptChange(SAMPLE_TRANSCRIPT);
          setMockListening(false);
        }, 1800);
      }
      return !prev;
    });
  }

  function buildSOAPText(): string {
    const planText = selectedPlanIds
      .map((id) => `  • ${allPlanLabels[id] ?? id}`)
      .join("\n");
    return `SOAP NOTE — ${new Date().toLocaleString("ko-KR")}
Patient: Mock patient
${finalDiagnosis ? `Final Diagnosis: ${finalDiagnosis}` : ""}
AI Engine: ${PROVIDER_INFO[usedProvider].label} (${PROVIDER_INFO[usedProvider].model})

[S] Subjective
${soap.subjective}

[O] Objective
${soap.objective}

[A] Assessment
${soap.assessment || (isDiagnosisConfirmed ? finalDiagnosis : "(Pending confirmation)")}

[P] Plan
${planText || soap.plan || "(Pending)"}

---
Generated by MedAI Scribe — Clinical Decision Support Tool
Final diagnosis must be confirmed by physician.`;
  }

  function buildJSON() {
    return JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        aiEngine: {
          provider: usedProvider,
          model: PROVIDER_INFO[usedProvider].model,
        },
        patient: { id: "PT-20240520-001" },
        transcript,
        soap: {
          subjective: soap.subjective,
          objective: soap.objective,
          assessment: isDiagnosisConfirmed ? finalDiagnosis : soap.assessment,
          plan: selectedPlanIds.map((id) => allPlanLabels[id] ?? id),
        },
        finalDiagnosis: isDiagnosisConfirmed ? finalDiagnosis : null,
        confirmedByPhysician: isDiagnosisConfirmed,
        disclaimer:
          "Clinical decision support tool only. Final diagnosis must be confirmed by physician.",
      },
      null,
      2
    );
  }

  async function copySOAP() {
    await navigator.clipboard.writeText(buildSOAPText());
    setCopyMsg("복사됨!");
    setTimeout(() => setCopyMsg(""), 2000);
  }

  function exportJSON() {
    const blob = new Blob([buildJSON()], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `soap_note_${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const lineCount = transcript.split("\n").filter((l) => l.trim()).length;
  const canAnalyze =
    !!transcript.trim() &&
    !isLoading &&
    (selectedProvider === "mock" || !!apiKey.trim());

  const providerInfo = PROVIDER_INFO[selectedProvider];

  return (
    <Card className="flex flex-col h-full border-slate-200 shadow-sm">
      <CardHeader className="pb-2 border-b border-slate-100">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <MessageSquare className="h-4 w-4 text-blue-600" />
            <CardTitle className="text-slate-700">진료 대화 기록</CardTitle>
          </div>
          <div className="flex items-center gap-1.5">
            {mockListening && (
              <Badge className="bg-red-500 text-white animate-pulse text-xs gap-1">
                <span className="inline-block h-1.5 w-1.5 rounded-full bg-white" />
                LIVE
              </Badge>
            )}
            {isLoading && (
              <Badge className="bg-blue-100 text-blue-700 border border-blue-200 text-xs gap-1">
                <Loader2 className="h-3 w-3 animate-spin" />
                분석 중
              </Badge>
            )}
            {!mockListening && !isLoading && isAnalyzed && (
              <Badge
                variant="secondary"
                className={`text-xs border ${PROVIDER_INFO[usedProvider].badgeBg}`}
              >
                {PROVIDER_INFO[usedProvider].shortLabel} · {lineCount}줄
              </Badge>
            )}
          </div>
        </div>
      </CardHeader>

      <CardContent className="flex flex-col gap-3 pt-3 flex-1 min-h-0 overflow-y-auto">
        <Textarea
          className="flex-1 min-h-[180px] font-mono text-xs leading-relaxed resize-none text-slate-700 bg-slate-50 border-slate-200 focus:bg-white"
          placeholder={`진료 대화를 입력하세요.\n\n예시 형식:\n환자: 증상 설명\n의사: 진찰 소견 / 검사 결과`}
          value={transcript}
          onChange={(e) => onTranscriptChange(e.target.value)}
          disabled={isLoading}
        />

        <div className="grid grid-cols-2 gap-2">
          <Button
            variant="outline"
            size="sm"
            className="gap-1.5 text-xs border-slate-300 text-slate-600 hover:bg-slate-100"
            onClick={loadSample}
            disabled={isLoading}
          >
            <FileText className="h-3.5 w-3.5" />
            샘플 대화 불러오기
          </Button>
          <Button
            variant="outline"
            size="sm"
            className={`gap-1.5 text-xs ${
              mockListening
                ? "border-red-300 text-red-600 bg-red-50 hover:bg-red-100"
                : "border-slate-300 text-slate-600 hover:bg-slate-100"
            }`}
            onClick={toggleMockVoice}
            disabled={isLoading}
          >
            {mockListening ? (
              <>
                <MicOff className="h-3.5 w-3.5" />
                중지
              </>
            ) : (
              <>
                <Mic className="h-3.5 w-3.5" />
                음성 입력 (Mock)
              </>
            )}
          </Button>
        </div>

        {/* AI Provider Selector */}
        <div className="border rounded-lg p-3 bg-slate-50/50 border-slate-200">
          <AIProviderSelector
            selectedProvider={selectedProvider}
            apiKey={apiKey}
            onProviderChange={onProviderChange}
            onApiKeyChange={onApiKeyChange}
          />
        </div>

        {/* Error message */}
        {analysisError && (
          <div className="flex items-start gap-2 rounded-md bg-red-50 border border-red-200 p-2.5 text-xs text-red-700">
            <AlertCircle className="h-3.5 w-3.5 shrink-0 mt-0.5" />
            <span>{analysisError}</span>
          </div>
        )}

        {/* Warning: API key missing */}
        {selectedProvider !== "mock" && !apiKey.trim() && (
          <p className="text-[10px] text-amber-600 flex items-center gap-1">
            <AlertCircle className="h-3 w-3" />
            API 키를 입력해야 분석 가능합니다
          </p>
        )}

        <Button
          className={`w-full gap-2 font-semibold text-sm ${
            canAnalyze
              ? `${providerInfo.bg} border ${providerInfo.border} ${providerInfo.color} hover:opacity-90`
              : "bg-slate-100 text-slate-400 cursor-not-allowed border border-slate-200"
          }`}
          size="sm"
          onClick={onAnalyze}
          disabled={!canAnalyze}
        >
          {isLoading ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin" />
              {PROVIDER_INFO[selectedProvider].shortLabel} 분석 중...
            </>
          ) : (
            <>
              <Play className="h-4 w-4" />
              {selectedProvider === "mock"
                ? "분석 실행"
                : `${PROVIDER_INFO[selectedProvider].shortLabel}로 분석`}
            </>
          )}
        </Button>

        <div className="border-t border-slate-100 pt-2">
          <p className="text-xs text-slate-400 font-medium mb-2 uppercase tracking-wider">
            Export
          </p>
          <div className="grid grid-cols-2 gap-2">
            <Button
              variant="outline"
              size="sm"
              className="gap-1.5 text-xs border-slate-300 text-slate-600 hover:bg-slate-100"
              onClick={copySOAP}
              disabled={!isAnalyzed}
            >
              <Clipboard className="h-3.5 w-3.5" />
              {copyMsg || "SOAP 복사"}
            </Button>
            <Button
              variant="outline"
              size="sm"
              className="gap-1.5 text-xs border-slate-300 text-slate-600 hover:bg-slate-100"
              onClick={exportJSON}
              disabled={!isAnalyzed}
            >
              <Download className="h-3.5 w-3.5" />
              JSON Export
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
